### ISSUE TITLE
Are there any EFI for Monterey

### ISSUE THREAD

**Issue by jchu2345** [md-siam/Legion_Y730_running_BigSur#2]
Thank you for providing Big Sur Y730 EFI!
I wish you can make a Monterey EFI so that I can work perfectly with this computer!
Thank you for watching!

**Comment by md-siam** [comment]
I have tried, but my Monterey EFI is unstable. 
I will release it when it's stable.

**Comment by jchu0952** [comment]
Ok thank you!
